global using System.Collections;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using CloudNativeCamp;
global using CloudNativeCamp.LinkedListImplementation;
global using CloudNativeCamp.LinkedListImplementation.SinglyLinkedList;
